name: Feature request
description: Suggest an improvement to Flowra CLI
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Flowra CLI. Please describe the feature you'd like.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: "It's hard to..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives you've tried or considered?
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else we should know?
