const path = require('path');

const { writeFile } = require('../utils/file-system');

const schema = [
  { key: 'APP_NAME', description: 'Human readable application name', defaultValue: 'flowra', required: true },
  { key: 'APP_ENV', description: 'Runtime environment (development, staging, production)', defaultValue: 'development', required: true },
  { key: 'APP_DEBUG', description: 'Enable verbose logging (true/false)', defaultValue: 'true', required: true },
  { key: 'APP_URL', description: 'Base URL used by outbound links', defaultValue: 'http://localhost:3387', required: true },
  { key: 'APP_PORT', description: 'HTTP server port', defaultValue: '3387', required: true },
  { key: 'APP_TIMEZONE', description: 'Default application timezone', defaultValue: 'Asia/Jakarta', required: true },
  { key: 'LOG_LEVEL', description: 'Logger severity threshold', defaultValue: 'info', required: false },
  { key: 'CORS_ORIGIN', description: 'Comma separated list of allowed origins', defaultValue: '*' },
  { key: 'SESSION_SECRET', description: 'Secret for signing sessions', required: false },
  { key: 'DB_CONNECTION_NAME', description: 'Default database connection alias', defaultValue: 'default', required: true },
  { key: 'DB_CONNECTIONS', description: 'Comma separated additional database aliases', defaultValue: '', required: false },
  { key: 'DB_CLIENT', description: 'Default database client (mysql2, pg, etc.)', defaultValue: 'mysql2', required: true },
  { key: 'DB_HOST', description: 'Default database host', defaultValue: '127.0.0.1', required: true },
  { key: 'DB_PORT', description: 'Default database port', defaultValue: '3306', required: true },
  { key: 'DB_USERNAME', description: 'Default database username', defaultValue: 'root', required: true },
  { key: 'DB_PASSWORD', description: 'Default database password', defaultValue: '', required: false },
  { key: 'DB_DATABASE', description: 'Default database name', defaultValue: 'flowra', required: true },
  { key: 'DB_SSL', description: 'Enable TLS/SSL for database connection', defaultValue: 'false', required: false },
  { key: 'CACHE_URL', description: 'Cache server connection string', required: false },
  { key: 'QUEUE_URL', description: 'Queue server connection string', required: false },
];

function buildExampleContents() {
  const lines = ['# Auto-generated by `flowra env:example`'];
  schema.forEach((entry) => {
    const description = `# ${entry.description}`;
    const value = entry.defaultValue ?? '';
    lines.push('', description, `${entry.key}=${value}`);
  });
  return `${lines.join('\n')}\n`;
}

function writeExample(targetPath = path.join(process.cwd(), '.env.example')) {
  const contents = buildExampleContents();
  writeFile(targetPath, contents);
  return targetPath;
}

function checkEnvironment(env = process.env) {
  const missing = schema
    .filter((entry) => entry.required)
    .filter((entry) => {
      const value = env[entry.key];
      return typeof value === 'undefined' || value === null || String(value).length === 0;
    })
    .map((entry) => entry.key);

  return { missing, total: schema.length };
}

module.exports = {
  schema,
  buildExampleContents,
  writeExample,
  checkEnvironment,
};
